name: ai_festival_ocr

services:
  ocr:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        HTTP_PROXY: http://${HTTP_PROXY}
        HTTPS_PROXY: http://${HTTPS_PROXY}
        NO_PROXY: ${no_proxy}
        PIP_INDEX_URL: ${PIP_INDEX_URL:-}
        PIP_TRUSTED_HOST: ${PIP_TRUSTED_HOST:-}
    container_name: ai_festival_ocr
    ports:
      - "10060:8000"
    env_file:
      - .env
    environment:
      HTTP_PROXY: http://${HTTP_PROXY}
      HTTPS_PROXY: http://${HTTPS_PROXY}
      NO_PROXY: ${no_proxy}
      http_proxy: http://${HTTP_PROXY}
      https_proxy: http://${HTTPS_PROXY}
      no_proxy: ${no_proxy}
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
